# 从编译项目通过、构建包内容

# 编译项目为docker镜像，然后推送到仓库中

# 定义stages
stages:
  - build # 编译
  - publish # 发布
  - deploy # 部署
  - undeploy # 撤销部署

variables:
  TAG: $CI_COMMIT_REF_NAME
  IMAGE_NAME: "wave"

  # 镜像仓库信息
  CI_IMG_REGISTRY: $CI_REGISTRY # 镜像仓库地址
  CI_IMG_REGISTRY_USER: $CI_REGISTRY_USER # 镜像仓库用户
  CI_IMG_REGISTRY_PWD: $CI_REGISTRY_PASSWORD # 镜像仓库密码
  CI_IMG_REGISTRY_ORG: $CI_REGISTRY_ORG # 镜像组织，没有则设置为/

include: 
  - local: ".gitlab/ci/common.yml"
  - local: ".gitlab/ci/docker-ci-dev.yml"
  - local: ".gitlab/ci/docker-ci-test.yml"
  - local: ".gitlab/ci/docker-ci-tag.yml"
 
